#!/bin/usr/env bash

javac vmsim.java;
frameNum=1024;
pageSize=4096;


for n in "1:1" "1:3" "3:1" "3:5" "5:3" "7:9" "9:7"
  do
    for j in "opt" "lru"
       do
          echo $n;
          java vmsim -a $j -n $frameNum -p $pageSize -s $n 3.trace;
          echo "\n";
       done
  done